# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-27 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yundongyuan', '0005_auto_20180527_1602'),
        ('chengji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChengjiSh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riqi', models.DateField(blank=True, default='2010-01-01', null=True, verbose_name='生化日期')),
                ('gaotong', models.FloatField(verbose_name='睾酮')),
                ('nandufen', models.FloatField(verbose_name='难度分')),
                ('wanchengfen', models.FloatField(verbose_name='完成分')),
                ('zongfen', models.FloatField(verbose_name='总分')),
                ('xingming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yundongyuan.Athlete', verbose_name='队员姓名')),
            ],
            options={
                'verbose_name': '成绩-生化',
                'verbose_name_plural': '成绩-生化',
            },
        ),
    ]
