# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-25 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yundongyuan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='achievement',
            field=models.CharField(default='', max_length=50, verbose_name='历年成绩'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='character',
            field=models.CharField(default='', max_length=50, verbose_name='特点'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='coach',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='教练'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='is_actice',
            field=models.BooleanField(default=True, verbose_name='是否为老师'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='join_date',
            field=models.DateField(blank=True, default='2012-01-01', null=True, verbose_name='入队日期'),
        ),
    ]
