# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-25 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yundongyuan', '0002_auto_20180525_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='birthday',
            field=models.DateField(blank=True, default='2010-01-01', null=True, verbose_name='出生年月'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='coach',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='主管教练'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='is_actice',
            field=models.BooleanField(default=True, verbose_name='在役'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='join_date',
            field=models.DateField(blank=True, default='2012-01-01', null=True, verbose_name='入队年月'),
        ),
    ]
