# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yundongyuan', '0003_auto_20180525_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='achievement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='历年成绩'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='character',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='特点'),
        ),
    ]
