# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-27 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yundongyuan', '0004_auto_20180525_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
    ]
