# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-25 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yundongyuan', '0004_auto_20180525_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShenghuaDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default='2010-01-01', null=True, verbose_name='检验日期')),
                ('gaotong', models.FloatField(verbose_name='睾酮')),
                ('pizhichun', models.FloatField(verbose_name='皮质醇')),
                ('niaosudan', models.FloatField(verbose_name='尿素氮')),
                ('jisuanjimei', models.FloatField(verbose_name='T/C')),
                ('tc', models.FloatField(verbose_name='肌酸激酶')),
                ('yichang', models.CharField(default='', max_length=50, verbose_name='异常数据说明')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yundongyuan.Athlete', verbose_name='运动员姓名')),
            ],
            options={
                'verbose_name': '生化指标',
                'verbose_name_plural': '生化指标',
            },
        ),
    ]
