# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-25 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shenghua', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shenghuadate',
            name='jisuanjimei',
            field=models.FloatField(verbose_name='肌酸激酶'),
        ),
        migrations.AlterField(
            model_name='shenghuadate',
            name='tc',
            field=models.FloatField(verbose_name='T/C'),
        ),
    ]
