# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-25 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunlian', '0002_xunliansh'),
    ]

    operations = [
        migrations.AddField(
            model_name='xunliandate',
            name='content',
            field=models.CharField(default='', max_length=50, verbose_name='训练内容'),
        ),
    ]
