# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunlian', '0004_xunliancj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xunliancj',
            name='sbyuanyin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='失败原因'),
        ),
    ]
